### ISSUE TITLE
Fatal error due to unintialized options

### ISSUE THREAD

**Issue by Alexia** [oOeyes/TippingOver#2]
Looks like TippingOver is not initializing its parser instance properly in all scenarios with a ParserOptions object.  So when it attempts to use $this->mOptions it produces a fatal error.

This occurred on Hearthstone wiki on several pages.  This example is from the Hunter article.

E_ERROR: Call to a member function getMaxIncludeSize() on a non-object

Sample stack trace
…:replaceVariables called at includes/parser/Parser.php (3139)
…:replaceVariables called at includes/parser/Parser.php (1216)
…er::internalParse called at includes/parser/Parser.php (602)
…ed at extensions/TippingOver/includes/WikiTooltips.php (338)
…ed at extensions/TippingOver/includes/WikiTooltips.php (367)
…ed at extensions/TippingOver/includes/WikiTooltips.php (478)
in WikiTooltips::checkAndAttachTooltip called at ? (?)
in call_user_func_array called at includes/Hooks.php (206)
in Hooks::run called at includes/GlobalFunctions.php (4013)
in wfRunHooks called at includes/Linker.php (252)
in Linker::link called at includes/OutputPage.php (1244)
…ge::addCategoryLinks called at includes/OutputPage.php (1591)
…ddParserOutputNoText called at includes/OutputPage.php (1644)
…utPage::addParserOutput called at includes/Article.php (639)
…rticle::view called at includes/actions/ViewAction.php (44)
in ViewAction::show called at includes/Wiki.php (428)
in MediaWiki::performAction called at includes/Wiki.php (292)
… MediaWiki::performRequest called at includes/Wiki.php (588)
in MediaWiki::main called at includes/Wiki.php (447)
in MediaWiki::run called at index.php (46)

**Comment by oOeyes** [comment]
Switched over to a cloned parser instance so that the parse method is safe to call rather than having to rely on recursiveTagParse, mimicking the approach used in the core message cache.  Parser options are now explicitly provided in the call.
