### ISSUE TITLE
Parser being called recursively.

### ISSUE THREAD

**Issue by Alexia** [oOeyes/TippingOver#6]
There is a fatal bug in the new 0.62.  I reverted TippingOver to 0.61 on Hydra since it was crashing the stack.

![s9aeiuxtlhl0](https://cloud.githubusercontent.com/assets/248632/17028925/c9ba3892-4f2e-11e6-813c-94176e74cb84.png)

**Comment by oOeyes** [comment]
Tooltip attachment to links inside tooltips may cause this issue if it's the first tooltip to be processed on the page, but tooltip attachment inside a tooltip isn't useful anyway. The new version, 0.63, now disables tooltip attachment when tooltip content is parsed.

**Comment by Alexia** [comment]
This is deployed to live Hydra.
